version: '3.8'

services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./user-service:/app/user-service
    depends_on:
      - user_service
    environment:
      - TZ=Europe/Moscow

  user_service:
    build: ./user-service
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - TZ=Europe/Moscow

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tests_user_service:
    build: ./user-service
    volumes:
      - ./user-service:/app
    command: pytest --cov=user_service tests/
    depends_on:
      - db
    environment:
      - FLASK_ENV=testing
      - TZ=Europe/Moscow

  tests_api_gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/app
      - ./user-service:/app/user-service
    command: pytest --cov=api_gateway tests/
    depends_on:
      - user_service
    environment:
      - FLASK_ENV=testing
      - TZ=Europe/Moscow

volumes:
  postgres_data: