# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import post_pb2 as proto_dot_post__pb2


class PostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/post.PostService/CreatePost',
                request_serializer=proto_dot_post__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.CreatePostResponse.FromString,
                )
        self.DeletePost = channel.unary_unary(
                '/post.PostService/DeletePost',
                request_serializer=proto_dot_post__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.DeletePostResponse.FromString,
                )
        self.UpdatePost = channel.unary_unary(
                '/post.PostService/UpdatePost',
                request_serializer=proto_dot_post__pb2.UpdatePostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.UpdatePostResponse.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/post.PostService/GetPost',
                request_serializer=proto_dot_post__pb2.GetPostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.GetPostResponse.FromString,
                )
        self.ListPosts = channel.unary_unary(
                '/post.PostService/ListPosts',
                request_serializer=proto_dot_post__pb2.ListPostsRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.ListPostsResponse.FromString,
                )
        self.ViewPost = channel.unary_unary(
                '/post.PostService/ViewPost',
                request_serializer=proto_dot_post__pb2.ViewPostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.ViewPostResponse.FromString,
                )
        self.LikePost = channel.unary_unary(
                '/post.PostService/LikePost',
                request_serializer=proto_dot_post__pb2.LikePostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.LikePostResponse.FromString,
                )
        self.CommentPost = channel.unary_unary(
                '/post.PostService/CommentPost',
                request_serializer=proto_dot_post__pb2.CommentPostRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.CommentPostResponse.FromString,
                )
        self.GetComments = channel.unary_unary(
                '/post.PostService/GetComments',
                request_serializer=proto_dot_post__pb2.GetCommentsRequest.SerializeToString,
                response_deserializer=proto_dot_post__pb2.GetCommentsResponse.FromString,
                )


class PostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommentPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=proto_dot_post__pb2.CreatePostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.CreatePostResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=proto_dot_post__pb2.DeletePostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.DeletePostResponse.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=proto_dot_post__pb2.UpdatePostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.UpdatePostResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=proto_dot_post__pb2.GetPostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.GetPostResponse.SerializeToString,
            ),
            'ListPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPosts,
                    request_deserializer=proto_dot_post__pb2.ListPostsRequest.FromString,
                    response_serializer=proto_dot_post__pb2.ListPostsResponse.SerializeToString,
            ),
            'ViewPost': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewPost,
                    request_deserializer=proto_dot_post__pb2.ViewPostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.ViewPostResponse.SerializeToString,
            ),
            'LikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.LikePost,
                    request_deserializer=proto_dot_post__pb2.LikePostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.LikePostResponse.SerializeToString,
            ),
            'CommentPost': grpc.unary_unary_rpc_method_handler(
                    servicer.CommentPost,
                    request_deserializer=proto_dot_post__pb2.CommentPostRequest.FromString,
                    response_serializer=proto_dot_post__pb2.CommentPostResponse.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=proto_dot_post__pb2.GetCommentsRequest.FromString,
                    response_serializer=proto_dot_post__pb2.GetCommentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'post.PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/CreatePost',
            proto_dot_post__pb2.CreatePostRequest.SerializeToString,
            proto_dot_post__pb2.CreatePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/DeletePost',
            proto_dot_post__pb2.DeletePostRequest.SerializeToString,
            proto_dot_post__pb2.DeletePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/UpdatePost',
            proto_dot_post__pb2.UpdatePostRequest.SerializeToString,
            proto_dot_post__pb2.UpdatePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/GetPost',
            proto_dot_post__pb2.GetPostRequest.SerializeToString,
            proto_dot_post__pb2.GetPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/ListPosts',
            proto_dot_post__pb2.ListPostsRequest.SerializeToString,
            proto_dot_post__pb2.ListPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/ViewPost',
            proto_dot_post__pb2.ViewPostRequest.SerializeToString,
            proto_dot_post__pb2.ViewPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/LikePost',
            proto_dot_post__pb2.LikePostRequest.SerializeToString,
            proto_dot_post__pb2.LikePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommentPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/CommentPost',
            proto_dot_post__pb2.CommentPostRequest.SerializeToString,
            proto_dot_post__pb2.CommentPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/post.PostService/GetComments',
            proto_dot_post__pb2.GetCommentsRequest.SerializeToString,
            proto_dot_post__pb2.GetCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
